name: dev-build
run-name: Build plugin for development
on: [push]
jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup latest PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Update decky-frontend-lib
        run: pnpm update decky-frontend-lib --latest

      - name: Build plugin
        run: |
          pnpm i
          pnpm run build

      - name: Upload plugin
        uses: actions/upload-artifact@v2
        with:
          name: plugin
          path: out/
